[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "streamlit run App/App.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
